### ISSUE TITLE
paypal-checkout-serversdk==1.0.1 => AttributeError: 'dict' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by wenbinf** [paypal/paypalhttp_python#10]
### General information

* SDK/Library version: paypal-checkout-serversdk==1.0.1
* Python Version: 3.10

### Issue description

tl;dr - The object_to_json function throws AttributeError: 'dict' object has no attribute '__dict__':

```python
 in object_to_json
    itr = json_data.__dict__.items()
AttributeError: 'dict' object has no attribute '__dict__'
```

A bit details:

- object_to_json is a method in the PayPalClient class from [Set Up Server-Side SDK](https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/) on PayPal.com, as of Dec 1, 2021.
- It's handy to convert the Result object to json in the code (e.g., processed in Python / Javascript)
- It used to work well in paypal-checkout-serversdk==1.0.0
- But in paypal-checkout-serversdk==1.0.1, it throws AttributeError: 'dict' object has no attribute '__dict__'

**Comment by devchristina** [comment]
Hi @wenbinf -- apologies that it's taken this long for anyone to reply from the PayPal side. Due to the age of this issue and the fact that this SDK is using old integration patterns & deprecated endpoints, I am going to close this issue without action and will add a "deprecated" status to the repo. Thank you for your understanding. If there are any issues you face, please let me know and we can look into it.
